import type { Metadata } from 'next';
import { LegalDoc, type LegalSection } from '../legal-doc';

export const metadata: Metadata = {
  title: 'Terms of Service — Pharma Ist',
  description: 'The terms that govern use of the Pharma Ist pharmacy management platform.',
};

const SECTIONS: LegalSection[] = [
  {
    heading: 'Acceptance of terms',
    body: [
      'These Terms of Service ("Terms") govern your access to and use of Pharma Ist ("the Service"), operated by Z2INFY Technologies ("we", "us", "our"). By creating an account or using the Service, you agree to these Terms on behalf of your pharmacy.',
      'If a separate written agreement exists between your pharmacy and Z2INFY Technologies, that agreement prevails where it conflicts with these Terms.',
    ],
  },
  {
    heading: 'Accounts and access',
    body: [
      'You are responsible for the accounts created under your pharmacy, including keeping credentials confidential and assigning appropriate roles. You must notify us promptly of any unauthorised use. You are responsible for the actions taken by users you grant access to.',
    ],
  },
  {
    heading: 'Acceptable use',
    body: [
      'You agree to use the Service lawfully and only for legitimate pharmacy operations. You must not:',
      {
        list: [
          'Use the Service to store or process data you are not authorised to handle.',
          'Attempt to breach, probe or circumvent the security of the Service.',
          'Interfere with or disrupt the integrity or performance of the Service.',
          'Reverse engineer, resell or sublicense the Service without our written consent.',
        ],
      },
    ],
  },
  {
    heading: 'Regulatory responsibility',
    body: [
      'The Service provides tools to help you operate your pharmacy, including registers and reports intended to support compliance. You remain solely responsible for complying with all applicable pharmacy, drug-control, tax and data-protection laws in your jurisdiction, and for verifying that records generated by the Service meet your regulatory obligations.',
    ],
  },
  {
    heading: 'Your data',
    body: [
      'You retain ownership of the data you enter into the Service. You grant us the limited rights needed to host and process that data to provide the Service. Our handling of personal data is described in the Privacy Policy.',
    ],
  },
  {
    heading: 'Service availability',
    body: [
      'We work to keep the Service available and reliable, but we do not guarantee uninterrupted access. We may perform maintenance, apply updates, or modify features. Where offline mode is enabled, it is provided on a best-effort basis and depends on your device and network.',
    ],
  },
  {
    heading: 'Fees',
    body: [
      'Access to paid plans is subject to the fees and billing terms communicated to your pharmacy. Fees are payable in advance unless otherwise agreed. Failure to pay may result in suspension or limitation of access.',
    ],
  },
  {
    heading: 'Limitation of liability',
    body: [
      'To the maximum extent permitted by law, the Service is provided "as is" without warranties of any kind. We are not liable for indirect, incidental or consequential damages, or for loss of profits or data, arising from your use of the Service. Nothing in these Terms excludes liability that cannot be excluded by law.',
    ],
  },
  {
    heading: 'Termination',
    body: [
      'You may stop using the Service at any time. We may suspend or terminate access if you breach these Terms or if required by law. On termination, your right to use the Service ends; data handling after termination is described in the Privacy Policy.',
    ],
  },
  {
    heading: 'Changes to these terms',
    body: [
      'We may update these Terms from time to time. When we make material changes, we will update the "Last updated" date above and, where appropriate, notify you within the Service. Continued use after changes take effect constitutes acceptance.',
    ],
  },
];

export default function TermsPage() {
  return (
    <LegalDoc
      title="Terms of Service"
      updated="3 October 2026"
      intro="These terms set out the rules for using Pharma Ist. Please read them carefully — using the Service means you accept them."
      sections={SECTIONS}
    />
  );
}
